SNSTopic:
  Type: AWS::SNS::Topic
  Properties:
    Subscription:
      - Endpoint: ${self:custom.snsEmailAddress}
        Protocol: email

DynamoDBTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.stackName}-images
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    StreamSpecification:
      StreamViewType: NEW_IMAGE
