#!/usr/bin/env bash

set -exo pipefail

function die {
  [ -n "${1}" ] && echo "${1}" >&2
  exit 1
}

AWS_DEFAULT_REGION=ap-southeast-1
stack_name="sls-vs-sam-stackup"
template_file="sam-output-template.yml"

docker-compose run --rm stackup \
  ${stack_name} up \
  --region ${AWS_DEFAULT_REGION} \
  --template ${template_file} \
  --capabilities CAPABILITY_IAM

